### ISSUE TITLE
[pdm/test] Python coverage comment does not link to the right file because of missing path prefix

### ISSUE THREAD

**Issue by niooss-ledger** [LedgerHQ/actions#137]
Hello,

When using `LedgerHQ/actions/pdm/test`, coverage comments are automatically added to the Pull Request (which is very nice).

But on Python projects using `src/` directory, the links are broken. For example on https://github.com/LedgerHQ/dnswatcher/pull/50#issuecomment-1983628093 , the first link to `__init__.py` goes to https://github.com/LedgerHQ/dnswatcher/blob/1cf040fed6aab5326cc0796e1bce978a7741a223/dnswatcher/__init__.py instead of https://github.com/LedgerHQ/dnswatcher/blob/1cf040fed6aab5326cc0796e1bce978a7741a223/src/dnswatcher/__init__.py (there is a missing `src/`).

The action https://github.com/MishaKav/pytest-coverage-comment/tree/v1.1.50 provides a parameter for such a use-case, named `coverage-path-prefix` (it is used to generate GitHub permalink URL: https://github.com/MishaKav/pytest-coverage-comment/blob/v1.1.50/src/parse.js#L294 ).

An easy fix would be to enable users of `LedgerHQ/actions/pdm/test` to provide `coverage-path-prefix` to `MishaKav/pytest-coverage-comment` (in https://github.com/LedgerHQ/actions/blob/1cec2f273472416aaa83eb835ed7487772a0ac94/pdm/test/action.yml)

Nevertheless, something more elegant could exist. For example, as the `pyproject.toml` contains [`[tool.pdm.build] package-dir = "src"`](https://github.com/LedgerHQ/python.copier/blob/33f8a9da4386ae02136c15a1ced48ead20e93cb6/template/pyproject.toml.jinja#L78) and [`[tool.coverage.run] source = ["src"]`](https://github.com/LedgerHQ/python.copier/blob/33f8a9da4386ae02136c15a1ced48ead20e93cb6/template/pyproject.toml.jinja#L328-L330), the action could (maybe?) request a setting to populate `coverage-path-prefix` automatically. What do you think?

**Comment by noirbizarre** [comment]
I think I already faced this one but not at Ledger. Most probably related to `coverage` config in the `pyproject.toml` file, will check this on https://github.com/LedgerHQ/python.copier
