### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by valpinkman** [LedgerHQ/actions#44]
We need to update `set-output` to use the new syntax before deprecation

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://stackoverflow.com/questions/61858388/how-do-i-set-an-enviroment-variable-in-github-action-on-a-windows-server/65110357#65110357

**Comment by noirbizarre** [comment]
Closing as there are no more `set-output` statements in our actions
